version: '3'

# RETI: Rete_interna (172.1.1.0/24), rete_esterna (172.1.2.0/24), rete_DMZ (172.1.3.0/24)
networks:
  rete_interna:
    name: rete_interna
    ipam:
      config:
        - subnet: 172.1.1.0/24  
  rete_esterna:
    name: rete_esterna
    ipam:
      config:
        - subnet: 172.1.2.0/24
  DMZ:
    name: rete_DMZ
    ipam:
      config:
        - subnet: 172.1.3.0/24

services:
   
#---------host rete interna
  
  interno:
    image: ubuntu:latest
    hostname: interno
    container_name: interno
    tty: true
    privileged: true
    command:  sh -c "apt-get update && apt-get install -y \
              bridge-utils net-tools iputils-ping nmap \
              traceroute telnet dnsutils nano tcpdump httpie && \
              ip route add 172.1.3.0/24 via 172.1.1.2 dev eth0 && \
              echo 'Host della rete interna' && bash"                                                         
    networks:
      rete_interna:
        ipv4_address: 172.1.1.3

#--------------host rete esterna
esterno:
    image: ubuntu:latest
    hostname: esterno
    container_name: esterno
    tty: true
    privileged: true
    command:  sh -c "apt-get update && apt-get install -y \
              bridge-utils net-tools iputils-ping nmap \
              traceroute telnet dnsutils nano tcpdump httpie && \
              ip route add 172.1.3.0/24 via 172.1.2.2 dev eth0 && \
              echo 'Host della rete esterna' && bash"                                                         
    networks:
      rete_esterna:
        ipv4_address: 172.1.2.3

#---------------------------------firewall esterno ASDASDASD
firewall_esterno:
    image: ubuntu:latest
    hostname: firewall_esterno
    container_name: firewall_esterno
    tty: true
    privileged: true
    command:  sh -c "apt-get update && apt-get install -y \ 
              bridge-utils net-tools iputils-ping nano \
              nmap iptables && sysctl -w net.ipv4.ip_forward=1 && \
              update-alternatives --set iptables /usr/sbin/iptables-legacy && \
              update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy && \ bash"
    volumes:
      - ./regole_est.sh:regole_est.sh
    networks:
      rete_esterna:
        ipv4_address: 172.1.2.2
      DMZ:
        ipv4_address: 172.1.3.2
#---------------------------------firewall interno
firewall_interno:
    image: ubuntu:latest
    hostname: firewall_interno
    container_name: firewall_interno
    tty: true
    privileged: true
    command:  sh -c "apt-get update && apt-get install -y \ 
              bridge-utils net-tools iputils-ping nano \
              nmap iptables && sysctl -w net.ipv4.ip_forward=1 && \
              update-alternatives --set iptables /usr/sbin/iptables-legacy && \
              update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy && \ bash"
    volumes:
      - ./regole_int.sh:regole_int.sh
    networks:
      rete_interna:
        ipv4_address: 172.1.1.2
      DMZ:
        ipv4_address: 172.1.3.2

#---------------------------------Honeypot Cowrie
cowrie:
    image: cowrie/cowrie
    container_name: cowrie
    ports:
      - "2222:2222"
    networks:
      rete_interna:
        DMZ:
          ipv4_address: 172.1.3.4

#---------------------------------Mailoney
mailoney:
    image: mailoney/mailoney
    container_name: mailoney
    ports:
      - "25:25"
    networks:
      DMZ:
        ipv4_address: 172.1.3.4