version: '3'

networks:
  rete_interna:
    name: rete_interna
    ipam:
      config:
        - subnet: 172.1.1.0/24  
  rete_esterna:
    name: rete_esterna
    ipam:
      config:
        - subnet: 172.1.2.0/24
  DMZ:
    name: rete_DMZ
    ipam:
      config:
        - subnet: 172.1.3.0/24

services:
#--------------host rete esterna
  esterno:
    image: ubuntu:latest
    hostname: esterno
    container_name: esterno
    tty: true
    privileged: true
    command:  sh -c "apt-get update && apt-get install -y \
              bridge-utils net-tools iputils-ping nmap iproute2 dnsutils \
              traceroute netcat telnet curl ftp nano hping3 && \
              ip route add 172.1.0.0/16 via 172.1.2.2 && \
              echo 'Host della rete esterna' && bash"                                                         
    networks:
      rete_esterna:
        ipv4_address: 172.1.2.3
   
#---------host1 rete interna
  interno1:
    image: ubuntu:latest
    hostname: interno1
    container_name: interno1
    tty: true
    privileged: true
    command:  sh -c "apt-get update && apt-get install -y \
              bridge-utils net-tools iputils-ping nmap iproute2 dnsutils \
              traceroute netcat telnet curl ftp nano hping3 && \
              ip route add 172.1.0.0/16 via 172.1.1.2 && \
              echo 'nameserver 172.1.3.4' > /etc/resolv.conf && \
              echo 'Host della rete interna' && bash"                                                         
    networks:
      rete_interna:
        ipv4_address: 172.1.1.3

#---------host2 rete interna
  interno2:
    image: ubuntu:latest
    hostname: interno2
    container_name: interno2
    tty: true
    privileged: true
    command:  sh -c "apt-get update && apt-get install -y \
              bridge-utils net-tools iputils-ping nmap iproute2 dnsutils\
              traceroute netcat telnet curl ftp nano hping3 && \
              ip route add 172.1.0.0/16 via 172.1.1.2 && \
              echo 'nameserver 172.1.3.4' > /etc/resolv.conf && \
              echo 'Host della rete interna' && bash"                                                         
    networks:
      rete_interna:
        ipv4_address: 172.1.1.5

#---------host rete DMZ
  
  HOST_DMZ:
    image: ubuntu:latest
    hostname: HOST_DMZ
    container_name:  HOST_DMZ
    tty: true
    privileged: true
    command:  sh -c "apt-get update && apt-get install -y \
              bridge-utils net-tools iputils-ping nmap iproute2 dnsutils \
              traceroute netcat telnet curl ftp nano hping3 && \
              ip route add 172.1.1.0/24 via 172.1.3.2 && \
              ip route add 172.1.2.0/24 via 172.1.3.7 && \
              echo 'nameserver 172.1.3.4' > /etc/resolv.conf && \
              echo 'Host della rete dmz' && bash"                                                         
   
    networks:
      DMZ:
        ipv4_address: 172.1.3.6

#---------------------------------firewall esterno
  firewall_esterno:
    image: ubuntu:latest
    hostname: firewall_esterno
    container_name: firewall_esterno
    tty: true
    privileged: true
    command:  sh -c "apt-get update && apt-get install -y bridge-utils ulogd2 iproute2 \ 
              net-tools nano iptables && sysctl -w net.ipv4.ip_forward=1 && \
              ip route add 172.1.1.0/24 via 172.1.3.2 && \
              /bin/bash /regole_est.sh && service ulogd2 restart && bash"
    volumes:
      - ./regole_est.sh:/regole_est.sh
      - ./ulogd.conf:/ulogd.conf
    networks:
      rete_esterna:
        ipv4_address: 172.1.2.2
      DMZ:
        ipv4_address: 172.1.3.7
#---------------------------------firewall interno
  firewall_interno:
    image: ubuntu:latest
    hostname: firewall_interno
    container_name: firewall_interno
    tty: true
    privileged: true
    command:  sh -c "apt-get update && apt-get install -y bridge-utils ulogd2 iproute2 \ 
              net-tools nano iptables && sysctl -w net.ipv4.ip_forward=1 && \
              ip route add 172.1.2.0/24 via 172.1.3.7 && \
              /bin/bash /regole_int.sh && service ulogd2 restart && bash"
    volumes:
      - ./regole_int.sh:/regole_int.sh
      - ./ulogd.conf:/ulogd.conf
    networks:
      rete_interna:
        ipv4_address: 172.1.1.2
      DMZ:
        ipv4_address: 172.1.3.2

#---------host rete DMZ
  
  DNS_DMZ:
    image: ubuntu:latest
    hostname: DNS_DMZ
    container_name: DNS_DMZ
    tty: true
    privileged: true
    command:  sh -c "apt-get update && apt-get install -y \
              bridge-utils net-tools iputils-ping nmap iproute2 \
              traceroute telnet curl ftp nano hping3 bind9 && \
              ip route add 172.1.1.0/24 via 172.1.3.2 && \
              ip route add 172.1.2.0/24 via 172.1.3.7 && \
              cp /etc/db.example.local /etc/bind/db.example.local && \
              cp /etc/named.conf /etc/bind/named.conf && \
              service named restart && bash" 
    volumes:
      - ./db.example.local:/etc/db.example.local  
      - ./named.conf:/etc/named.conf                                                  
    networks:
      DMZ:
        ipv4_address: 172.1.3.4


#---------------------------------Honeypot Mailoney
  mailoney:
    image: dtagdevsec/mailoney:alpha
    container_name: mailoney
    ports:
      - "25:25"
    privileged: true
    user: root
    networks:
      rete_interna:
        ipv4_address: 172.1.1.4
        
#---------------------------------Honeypot Dionaea
  dionaea:
    image: dinotools/dionaea
    privileged: true
    networks:
      DMZ:
        ipv4_address: 172.1.3.5

  #---------------------------------Web Server Apache
  web_server:
    image: linode/lamp
    hostname: web_server
    container_name: webserver
    tty: true
    privileged: true
    ports:
      - "80:80"
    command: sh -c "apt-get update && apt-get install -y \
             bridge-utils net-tools iputils-ping iproute2 && \
             ip route add 172.1.2.0/24 via 172.1.3.7 && \
             ip route add 172.1.1.0/24 via 172.1.3.2 && \
             service apache2 start && bash"
    networks:
      DMZ:
        ipv4_address: 172.1.3.3