version: '3'

# RETI: Rete_interna (172.1.1.0/24), rete_esterna (172.1.2.0/24), rete_DMZ (172.1.3.0/24)
networks:
  rete_interna:
    name: rete_interna
    ipam:
      config:
        - subnet: 172.1.1.0/24  
  rete_esterna:
    name: rete_esterna
    ipam:
      config:
        - subnet: 172.1.2.0/24
  DMZ:
    name: rete_DMZ
    ipam:
      config:
        - subnet: 172.1.3.0/24

services:
#--------------host rete esterna
  esterno:
    image: ubuntu:latest
    hostname: esterno
    container_name: esterno
    tty: true
    privileged: true
    command:  sh -c "apt-get update && apt-get install -y \
              bridge-utils net-tools iputils-ping nmap iproute2 \
              traceroute telnet ssh curl ftp nano httpie && \
              ip route add 172.1.0.0/16 via 172.1.2.2 && \
              echo 'Host della rete esterna' && bash"                                                         
    networks:
      rete_esterna:
        ipv4_address: 172.1.2.3
   
#---------host rete interna
  
  interno:
    image: ubuntu:latest
    hostname: interno
    container_name: interno
    tty: true
    privileged: true
    command:  sh -c "apt-get update && apt-get install -y \
              bridge-utils net-tools iputils-ping nmap iproute2 \
              traceroute telnet ssh curl ftp nano httpie && \
              ip route add 172.1.0.0/16 via 172.1.1.2 && \
              echo 'Host della rete interna' && bash"                                                         
    networks:
      rete_interna:
        ipv4_address: 172.1.1.3

#---------host rete DMZ
  
  HOST_DMZ:
    image: ubuntu:latest
    hostname: HOST_DMZ
    container_name:  HOST_DMZ
    tty: true
    privileged: true
    command:  sh -c "apt-get update && apt-get install -y \
              bridge-utils net-tools iputils-ping nmap iproute2 \
              traceroute telnet ssh curl ftp nano httpie && \
              ip route add 172.1.1.0/24 via 172.1.3.7 && \
              ip route add 172.1.2.0/24 via 172.1.3.2 && \
              echo 'Host della rete dmz' && bash"                                                         
    networks:
      DMZ:
        ipv4_address: 172.1.3.8

#---------------------------------firewall esterno
  firewall_esterno:
    image: ubuntu:latest
    hostname: firewall_esterno
    container_name: firewall_esterno
    tty: true
    privileged: true
    command:  sh -c "apt-get update && apt-get install -y bridge-utils ulogd2 \ 
              net-tools nano iptables && sysctl -w net.ipv4.ip_forward=1 && \
              /bin/bash /regole_est.sh && service ulogd2 restart && bash"
    volumes:
      - ./regole_est.sh:/regole_est.sh
      - ./ulogd.conf:/ulogd.conf
    networks:
      rete_esterna:
        ipv4_address: 172.1.2.2
      DMZ:
        ipv4_address: 172.1.3.2
#---------------------------------firewall interno
  firewall_interno:
    image: ubuntu:latest
    hostname: firewall_interno
    container_name: firewall_interno
    tty: true
    privileged: true
    command:  sh -c "apt-get update && apt-get install -y bridge-utils ulogd2 \ 
              net-tools nano iptables && sysctl -w net.ipv4.ip_forward=1 && \
              /bin/bash /regole_int.sh && service ulogd2 restart && bash"
    volumes:
      - ./regole_int.sh:/regole_int.sh
      - ./ulogd.conf:/ulogd.conf
    networks:
      rete_interna:
        ipv4_address: 172.1.1.2
      DMZ:
        ipv4_address: 172.1.3.7

#---------------------------------Honeypot Cowrie
  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie
    ports:
      - "2222:2222"
    networks:
        DMZ:
          ipv4_address: 172.1.3.4
#---------------------------------Mailoney
  mailoney:
    image: dtagdevsec/mailoney:alpha
    container_name: mailoney
    ports:
      - "25:25"
    user: root
    networks:
      DMZ:
        ipv4_address: 172.1.3.5
        
#---------------------------------FTP Server
  ftp_server:
    image: fauria/vsftpd
    ports:
      - "21:21"  # Porta FTP
    environment:
      - FTP_USER=username
      - FTP_PASS=password
    networks:
      DMZ:
        ipv4_address: 172.1.3.6

  #---------------------------------Web Server Apache
  web_server:
    image: linode/lamp
    hostname: web_server
    container_name: webserver
    tty: true
    privileged: true
    ports:
      - "80:80"
    command: sh -c "apt-get update && apt-get install -y \
             bridge-utils net-tools iputils-ping iproute2 && \
             ip route add 172.1.2.0/24 via 172.1.3.2 && \
             ip route add 172.1.1.0/24 via 172.1.3.7 && \
             service apache2 start && bash"
    networks:
      DMZ:
        ipv4_address: 172.1.3.3