#
# Dockerfile: host della dmz
#

FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
  bridge-utils \
  net-tools \
  iputils-ping \
  nmap \
  traceroute \
  telnet \
  dnsutils \
  nano \
  tcpdump \
  httpie  
  
CMD echo "Host in DMZ - host_dmz" 


 
