version: '3'

# RETI: Rete_interna (172.1.1.0/24), rete_esterna (172.1.2.0/24), rete_DMZ (172.1.3.0/24)
networks:
  rete_interna:
    name: rete_interna
    ipam:
      config:
        - subnet: 172.1.1.0/24  
  rete_esterna:
    name: rete_esterna
    ipam:
      config:
        - subnet: 172.1.2.0/24
  DMZ:
    name: rete_DMZ
    ipam:
      config:
        - subnet: 172.1.3.0/24

services:
#-------------------------------------------- FIREWALL con IPTables

  firewall:
    image: ubuntu:latest
    hostname: myfirewall
    container_name: firewall
    tty: true
    privileged: true
    command: sh -c "apt-get update && \
                    apt-get install -y \ 
                                        bridge-utils \
                                        net-tools \
                                        iputils-ping \
                                        nano \
                                        nmap \
                                        iptables && \
                                        sysctl -w net.ipv4.ip_forward=1 && \
                                        update-alternatives --set iptables /usr/sbin/iptables-legacy && \
                                        update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy && \
                                        bash"
    volumes:
      - ./regole.sh:/firewall/regole.sh
    networks:
      rete_interna:
        ipv4_address: 172.1.1.2
      rete_esterna:
        ipv4_address: 172.1.2.2
      DMZ:
        ipv4_address: 172.1.3.2

   
#-------------------------------------------- host rete interna: 172.1.1.3
  
  interno1:
    image: ubuntu:latest
    hostname: interno1
    container_name: interno1
    tty: true
    privileged: true
    command: sh -c "apt-get update && \
                    apt-get install -y \
                                          bridge-utils \
                                          net-tools \
                                          iputils-ping \
                                          nmap \
                                          iproute2 && \
                    ip route add 172.1.0.0/16 via 172.1.1.2 dev eth0 && \
                    bash"
                    
    networks:
      rete_interna:
        ipv4_address: 172.1.1.3
    
#-------------------------------------------- host rete esterna : (cliente 172.1.2.3) attaccante (172.1.2.4) 

  client1:
    image: ubuntu:latest
    hostname: client1
    container_name: client1
    tty: true
    privileged: true
    command: sh -c "apt-get update && \
                    apt-get install -y \
                                          bridge-utils \
                                          net-tools \
                                          iputils-ping \
                                          nmap \
                                          curl \
                                          iproute2 && \
                    ip route add 172.1.0.0/16 via 172.1.2.2 dev eth0 && \
                    bash"
    networks:
      rete_esterna:
        ipv4_address: 172.1.2.3
  

  attaccante1:
    image: ubuntu:latest
    hostname: attaccante1
    container_name: attaccante1
    tty: true
    privileged: true
    command: sh -c "apt-get update && \
                    apt-get install -y \
                                          bridge-utils \
                                          net-tools \
                                          iputils-ping \
                                          nmap \
                                          iproute2 \
                                          python3-pip && \
                    ip route add 172.1.0.0/16 via 172.1.2.2 dev eth0 && \
                    bash"
    volumes:
      - ./slowloris:/slowloris
    networks:
      rete_esterna:
        ipv4_address: 172.1.2.4
    
#-------------------------------------------- Server DMZ : 172.1.3.3

  server1:
    image: linode/lamp
    hostname: server1
    container_name: server1
    tty: true
    privileged: true
    ports:
      - "80:80"
    command: sh -c "apt-get update && \
                    apt-get install -y \
                                          bridge-utils \
                                          net-tools \
                                          iputils-ping \
                                          iproute2 && \
                    ip route add 172.1.0.0/16 via 172.1.3.2 dev eth0 && \
                    service apache2 start && \
                    bash"
    networks:
      DMZ:
        ipv4_address: 172.1.3.3