#
# Dockerfile: host 1 della rete interna
#

FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
  bridge-utils \
  net-tools \
  iputils-ping \
  nmap \
  traceroute \
  telnet \
  dnsutils \
  nano \
  tcpdump \
  httpie
   
CMD echo "Host in rete interna - host_int1"

 
